/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectofinalnutricionistagrupo93.Vistas;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import proyectofinalnutricionistagrupo93.AccesoADatos.Data_Comidas;
import proyectofinalnutricionistagrupo93.AccesoADatos.Data_Dieta;
import proyectofinalnutricionistagrupo93.AccesoADatos.Data_DietaComida;
import proyectofinalnutricionistagrupo93.Entidades.Comida;
import proyectofinalnutricionistagrupo93.Entidades.Dieta;
import proyectofinalnutricionistagrupo93.Entidades.DietaComida;
import proyectofinalnutricionistagrupo93.Entidades.Horario;

/**
 *
 * @author Zennon
 */
public class Registro_De_ComidasDieta extends javax.swing.JInternalFrame {

   
    protected Data_Dieta Data_Dieta = new Data_Dieta();
    protected ArrayList<Dieta> listaDieta = new ArrayList<>();
    protected Dieta dietaActual = null;
    protected Data_Comidas Data_Comida = new Data_Comidas();
    protected ArrayList<Comida> listaPaci = new ArrayList<>();
    protected Comida comidaActual = null;
    protected Data_DietaComida Data_DietaComida = new Data_DietaComida();
    protected DietaComida dietaComidaActual = null;
    protected ArrayList<Horario> listaHorarios = new ArrayList<>();
    /**
     * Creates new form Registro_De_ComidasDieta
     */
    public Registro_De_ComidasDieta() {
        initComponents();
        List<Dieta> listaDieta = Data_Dieta.listaDietasActivas();
        cargarDatosDieta((ArrayList<Dieta>) listaDieta);
        List<Comida> listaComida = Data_Comida.listaComida();
        cargarDatosComida((ArrayList<Comida>) listaComida);
        cargarDatosHorario();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlDietas = new javax.swing.JLabel();
        jcbDietas = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jcbComida = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jcbHorarios = new javax.swing.JComboBox<>();
        jAgregarComidas = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jtPorcion = new javax.swing.JTextField();
        jSalir = new javax.swing.JButton();
        jbLimpiar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Registro De Comidas Por Dieta");

        jlDietas.setText("Nombre de la dieta :");

        jcbDietas.setToolTipText("");
        jcbDietas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbDietasActionPerformed(evt);
            }
        });

        jLabel2.setText("Comida");

        jcbComida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbComidaActionPerformed(evt);
            }
        });

        jLabel3.setText("Horario");

        jcbHorarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbHorariosActionPerformed(evt);
            }
        });

        jAgregarComidas.setText("Agregar");
        jAgregarComidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAgregarComidasActionPerformed(evt);
            }
        });

        jLabel7.setText("Porcion :");

        jtPorcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtPorcionActionPerformed(evt);
            }
        });

        jSalir.setText("Salir");
        jSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSalirActionPerformed(evt);
            }
        });

        jbLimpiar.setText("Limpiar");
        jbLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jlDietas)
                        .addGap(18, 18, 18)
                        .addComponent(jcbDietas, 0, 252, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtPorcion)
                                .addGap(6, 6, 6))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jcbComida, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jAgregarComidas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbLimpiar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSalir)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(jLabel3)
                    .addGap(18, 18, 18)
                    .addComponent(jcbHorarios, 0, 312, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlDietas)
                    .addComponent(jcbDietas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jcbComida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jtPorcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jAgregarComidas)
                    .addComponent(jSalir)
                    .addComponent(jbLimpiar))
                .addGap(15, 15, 15))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(57, 57, 57)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jcbHorarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(191, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcbDietasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbDietasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbDietasActionPerformed

    private void jcbComidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbComidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbComidaActionPerformed

    private void jcbHorariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbHorariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbHorariosActionPerformed

    private void jAgregarComidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAgregarComidasActionPerformed
        try {
            int dietaIndex = jcbDietas.getSelectedIndex();
            Dieta dietaSeleccionado = (Dieta) jcbDietas.getItemAt(dietaIndex);
            int comidandex = jcbComida.getSelectedIndex();
            Comida ComidaSeleccionado = (Comida) jcbComida.getItemAt(comidandex);
            int horarioIndex = jcbHorarios.getSelectedIndex();
            Horario horarioSeleccionado = (Horario) jcbHorarios.getItemAt(horarioIndex);
            
            Integer porcion = Integer.parseInt(jtPorcion.getText());
           
            Boolean estado = true;

            if (porcion == null) {
                JOptionPane.showMessageDialog(null, "No puede haber campos de porcion vacios.");
                return;
            }
            if (dietaComidaActual == null) {
                dietaComidaActual = new DietaComida(ComidaSeleccionado.getIdComida(), dietaSeleccionado.getIdDieta(), horarioSeleccionado, porcion, estado);
                Data_DietaComida.agregarDietaComida(dietaComidaActual);
            }else {
            //modificar dietacomida
            }

        } catch (Exception e) {
JOptionPane.showMessageDialog(null, "No puede agregar nueva DietaComida.");
                
        }

    }//GEN-LAST:event_jAgregarComidasActionPerformed

    private void jtPorcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtPorcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtPorcionActionPerformed

    private void jSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSalirActionPerformed
        dispose();
    }//GEN-LAST:event_jSalirActionPerformed

    private void jbLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimpiarActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_jbLimpiarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAgregarComidas;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton jSalir;
    private javax.swing.JButton jbLimpiar;
    private javax.swing.JComboBox<Comida> jcbComida;
    private javax.swing.JComboBox<Dieta> jcbDietas;
    private javax.swing.JComboBox<Horario> jcbHorarios;
    private javax.swing.JLabel jlDietas;
    private javax.swing.JTextField jtPorcion;
    // End of variables declaration//GEN-END:variables
 private void cargarDatosDieta(ArrayList<Dieta> listaDieta) {
        listaDieta.forEach((d) -> {
            jcbDietas.addItem(d);
        });
    }

    private void cargarDatosComida(ArrayList<Comida> listaComida) {
        listaComida.forEach((c) -> {
            jcbComida.addItem(c);
        });
    }
       private void cargarDatosHorario() {
         for (Horario aux : Horario.values()) {
            jcbHorarios.addItem(aux);
        }
    }
    

    private void limpiarCampos() {
        jtPorcion.setText("");
    }
}
