
package proyectofinalnutricionistagrupo93.Vistas;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import proyectofinalnutricionistagrupo93.AccesoADatos.Data_Comidas;
import proyectofinalnutricionistagrupo93.AccesoADatos.Data_Dieta;
import proyectofinalnutricionistagrupo93.AccesoADatos.Data_DietaComida;
import proyectofinalnutricionistagrupo93.Entidades.Comida;
import proyectofinalnutricionistagrupo93.Entidades.Dieta;
import proyectofinalnutricionistagrupo93.Entidades.DietaComida;

public class Registro_De_DietaComida extends javax.swing.JInternalFrame {

     private DefaultTableModel modeloTabla = new DefaultTableModel();
    protected Data_Dieta Data_Dieta = new Data_Dieta();
    protected ArrayList<Dieta> listaDieta = new ArrayList<>();
    protected Dieta dietaActual = null;
    protected Data_Comidas Data_Comida = new Data_Comidas();
    protected ArrayList<Comida> listaPaci = new ArrayList<>();
    protected Comida comidaActual = null;
    protected Data_DietaComida Data_DietaComida = new Data_DietaComida();
    protected DietaComida dietaComidaActual = null;

    public Registro_De_DietaComida() {
        initComponents();
        List<Dieta> listaDieta = Data_Dieta.listaDietasActivas();
        cargarDatosDieta((ArrayList<Dieta>) listaDieta);
        List<Comida> listaComida = Data_Comida.listaComida();
        cargarDatosComida((ArrayList<Comida>) listaComida);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtPorcionM = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jtPorcionA = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jtPorcionD = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtPorcionC = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jcbCena = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        jcbSnack = new javax.swing.JComboBox<>();
        jcbMerienda = new javax.swing.JComboBox<>();
        jcbAlmuerzo = new javax.swing.JComboBox<>();
        jcbDesayuno = new javax.swing.JComboBox<>();
        jSalir = new javax.swing.JButton();
        jAgregarComidas = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jbLimpiar = new javax.swing.JButton();
        jtPorcionS = new javax.swing.JTextField();
        jlDietas = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jcbDietas = new javax.swing.JComboBox<>();

        setIconifiable(true);
        setTitle("Registro de DietaComida");

        jtPorcionM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtPorcionMActionPerformed(evt);
            }
        });

        jLabel9.setText("Porcion :");

        jtPorcionA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtPorcionAActionPerformed(evt);
            }
        });

        jLabel8.setText("Porcion :");

        jtPorcionD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtPorcionDActionPerformed(evt);
            }
        });

        jLabel7.setText("Porcion :");

        jtPorcionC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtPorcionCActionPerformed(evt);
            }
        });

        jLabel20.setText("Porcion :");

        jcbCena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbCenaActionPerformed(evt);
            }
        });

        jLabel19.setText("Cena :");

        jcbSnack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbSnackActionPerformed(evt);
            }
        });

        jcbDesayuno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbDesayunoActionPerformed(evt);
            }
        });

        jSalir.setText("Salir");
        jSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSalirActionPerformed(evt);
            }
        });

        jAgregarComidas.setText("Agregar");
        jAgregarComidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAgregarComidasActionPerformed(evt);
            }
        });

        jLabel5.setText("Snack");

        jLabel4.setText("Merienda :");

        jLabel3.setText("Almuerzo");

        jLabel2.setText("Desayuno");

        jbLimpiar.setText("Limpiar");
        jbLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimpiarActionPerformed(evt);
            }
        });

        jtPorcionS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtPorcionSActionPerformed(evt);
            }
        });

        jlDietas.setText("Nombre de la dieta :");

        jLabel10.setText("Porcion :");

        jcbDietas.setToolTipText("");
        jcbDietas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbDietasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 438, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jlDietas)
                            .addGap(18, 18, 18)
                            .addComponent(jcbDietas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5)
                                .addComponent(jLabel2)
                                .addComponent(jLabel19))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jcbMerienda, javax.swing.GroupLayout.Alignment.LEADING, 0, 149, Short.MAX_VALUE)
                                .addComponent(jcbAlmuerzo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jcbDesayuno, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jcbSnack, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jcbCena, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(58, 58, 58)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel20)
                                    .addGap(18, 18, 18)
                                    .addComponent(jtPorcionC))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addGap(18, 18, 18)
                                    .addComponent(jtPorcionD))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addGap(18, 18, 18)
                                    .addComponent(jtPorcionA))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addGap(18, 18, 18)
                                    .addComponent(jtPorcionM))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel10)
                                    .addGap(18, 18, 18)
                                    .addComponent(jtPorcionS))))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jAgregarComidas)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jbLimpiar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 215, Short.MAX_VALUE)
                            .addComponent(jSalir)))
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlDietas)
                        .addComponent(jcbDietas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jtPorcionD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jcbDesayuno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jtPorcionA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jcbAlmuerzo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jtPorcionM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jcbMerienda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5)
                                .addComponent(jcbSnack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jcbCena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel20))
                                .addComponent(jLabel19)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel10)
                                .addComponent(jtPorcionS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jtPorcionC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jAgregarComidas)
                        .addComponent(jSalir)
                        .addComponent(jbLimpiar))
                    .addContainerGap(18, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtPorcionMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtPorcionMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtPorcionMActionPerformed

    private void jtPorcionAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtPorcionAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtPorcionAActionPerformed

    private void jtPorcionDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtPorcionDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtPorcionDActionPerformed

    private void jtPorcionCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtPorcionCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtPorcionCActionPerformed

    private void jcbCenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbCenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbCenaActionPerformed

    private void jcbSnackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbSnackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbSnackActionPerformed

    private void jcbDesayunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbDesayunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbDesayunoActionPerformed

    private void jSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSalirActionPerformed
        dispose();
    }//GEN-LAST:event_jSalirActionPerformed

    private void jAgregarComidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAgregarComidasActionPerformed
        try {
            int dietaIndex = jcbDietas.getSelectedIndex();
            Dieta dietaSeleccionado = (Dieta) jcbDietas.getItemAt(dietaIndex);
            int desayunondex = jcbDietas.getSelectedIndex();
            Comida desayunoSeleccionado = (Comida) jcbDesayuno.getItemAt(dietaIndex);
            int almuerzoIndex = jcbDietas.getSelectedIndex();
            Comida almuerzoSeleccionado = (Comida) jcbAlmuerzo.getItemAt(almuerzoIndex);
            int meriendaIndex = jcbDietas.getSelectedIndex();
            Comida meriendaSeleccionado = (Comida) jcbMerienda.getItemAt(meriendaIndex);
            int cenaIndex = jcbDietas.getSelectedIndex();
            Comida cenaSeleccionado = (Comida) jcbCena.getItemAt(cenaIndex);
            int snackIndex = jcbDietas.getSelectedIndex();
            Comida snackSeleccionado = (Comida) jcbSnack.getItemAt(snackIndex);
            Integer porcionD = Integer.parseInt(jtPorcionD.getText());
            Integer porcionA = Integer.parseInt(jtPorcionA.getText());
            Integer porcionM = Integer.parseInt(jtPorcionM.getText());
            Integer porcionS = Integer.parseInt(jtPorcionS.getText());
            Integer porcionC = Integer.parseInt(jtPorcionC.getText());
            Boolean estado = true; 
            
            if(porcionA == null || porcionC == null || porcionD == null || porcionM == null || porcionS == null){
                 JOptionPane.showMessageDialog(null, "No puede haber campos de porcion vacios.");
                return;
            }
            if (dietaComidaActual == null) {
                dietaComidaActual = new DietaComida(desayunoSeleccionado.getIdComida(),dietaSeleccionado.getIdDieta(),null,porcionA,estado);
                Data_DietaComida.agregarDietaComida(dietaComidaActual);
            }
            
            
        } catch (Exception e) {
                
                }
        
        
        
        
        
    }//GEN-LAST:event_jAgregarComidasActionPerformed

    private void jbLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimpiarActionPerformed
       limpiarCampos();
    }//GEN-LAST:event_jbLimpiarActionPerformed

    private void jtPorcionSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtPorcionSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtPorcionSActionPerformed

    private void jcbDietasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbDietasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbDietasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAgregarComidas;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton jSalir;
    private javax.swing.JButton jbLimpiar;
    private javax.swing.JComboBox<Comida> jcbAlmuerzo;
    private javax.swing.JComboBox<Comida> jcbCena;
    private javax.swing.JComboBox<Comida> jcbDesayuno;
    private javax.swing.JComboBox<Dieta> jcbDietas;
    private javax.swing.JComboBox<Comida> jcbMerienda;
    private javax.swing.JComboBox<Comida> jcbSnack;
    private javax.swing.JLabel jlDietas;
    private javax.swing.JTextField jtPorcionA;
    private javax.swing.JTextField jtPorcionC;
    private javax.swing.JTextField jtPorcionD;
    private javax.swing.JTextField jtPorcionM;
    private javax.swing.JTextField jtPorcionS;
    // End of variables declaration//GEN-END:variables
 private void cargarDatosDieta(ArrayList<Dieta> listaDieta) {
       listaDieta.forEach((d) -> {
            jcbDietas.addItem(d);
        });
    }

    private void cargarDatosComida(ArrayList<Comida> listaComida) {
        listaComida.forEach((c) -> {
            jcbDesayuno.addItem(c);
            jcbSnack.addItem(c);
            jcbDesayuno.addItem(c);
            jcbMerienda.addItem(c);
            jcbAlmuerzo.addItem(c);
            jcbCena.addItem(c);
        });
    }
    private void limpiarCampos() {
        jtPorcionA.setText("");
        jtPorcionC.setText("");
        jtPorcionD.setText("");
        jtPorcionM.setText("");
        jtPorcionS.setText("");      
        
    }
}
